name: Main workflow
on: push
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4  
      - name: Build
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions: 
      packages: write
    steps:
      - name: Download repo
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: Build docker
        run: bash ci/build-docker.sh
      - name: Push docker
        run: bash ci/push-docker.sh
    
          
        
        
     
        
